spring.application.name=apigerman

# Conexion a PostgreSQL Supabase
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

app.pagination.page-size=${APP_PAGE_SIZE}
app.pagination.page-number=${APP_PAGE_NUMBER}