url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
username=postgres.zbjfwfjdayoinvzplklj
password=ILyhK51ziEbixHCR
driver=org.postgresql.Driver
changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml